# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iphone.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 600)
        MainWindow.setMinimumSize(QtCore.QSize(300, 500))
        MainWindow.setMaximumSize(QtCore.QSize(300, 600))
        MainWindow.setSizeIncrement(QtCore.QSize(239, 490))
        MainWindow.setBaseSize(QtCore.QSize(239, 490))
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        MainWindow.setWindowTitle("")
        MainWindow.setStyleSheet("background:transparent;\n"
"\n"
"border-radius:15px 50px;\n"
"\n"
"Qt::WA_TranslucentBackground, true;\n"
"border-color: rgb(0, 0, 0);\n"
"    ")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background:transparent;\n"
"border-radius:15px")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-170, -250, 961, 1041))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("iphonexdesign-800x669.png"))
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 450, 51, 51))
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.on_click5)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 450, 51, 51))
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.on_click6)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 450, 51, 51))
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.on_click7)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(90, 450, 51, 51))
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.on_click8)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(200, 250, 51, 51))
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.on_click9)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(150, 300, 51, 51))
        self.pushButton_10.setAutoFillBackground(False)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    \n"
" \n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.on_click10)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(90, 310, 51, 51))
        self.pushButton_11.setAutoFillBackground(False)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(self.on_click11)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(50, 300, 51, 51))
        self.pushButton_12.setAutoFillBackground(False)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.on_click12)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(150, 250, 51, 51))
        self.pushButton_13.setAutoFillBackground(False)
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.on_click13)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(90, 250, 51, 51))
        self.pushButton_14.setAutoFillBackground(False)
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.clicked.connect(self.on_click14)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(40, 250, 51, 51))
        self.pushButton_15.setAutoFillBackground(False)
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.clicked.connect(self.on_click15)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(200, 190, 51, 51))
        self.pushButton_16.setAutoFillBackground(False)
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.clicked.connect(self.on_click16)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(140, 190, 51, 51))
        self.pushButton_17.setAutoFillBackground(False)
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.clicked.connect(self.on_click17)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(100, 130, 51, 51))
        self.pushButton_18.setAutoFillBackground(False)
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_18.clicked.connect(self.on_click18)
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(50, 190, 51, 51))
        self.pushButton_19.setAutoFillBackground(False)
        self.pushButton_19.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_19.clicked.connect(self.on_click19)
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(40, 130, 51, 51))
        self.pushButton_20.setAutoFillBackground(False)
        self.pushButton_20.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_20.clicked.connect(self.on_click20)
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(90, 190, 51, 51))
        self.pushButton_21.setAutoFillBackground(False)
        self.pushButton_21.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_21.clicked.connect(self.on_click21)
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(150, 130, 51, 51))
        self.pushButton_22.setAutoFillBackground(False)
        self.pushButton_22.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_22.clicked.connect(self.on_click22)
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(200, 120, 51, 51))
        self.pushButton_23.setAutoFillBackground(False)
        self.pushButton_23.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_23.setText("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_23.clicked.connect(self.on_click23)
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(40, 70, 51, 51))
        self.pushButton_24.setAutoFillBackground(False)
        self.pushButton_24.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_24.setText("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_24.clicked.connect(self.on_click24)
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(100, 70, 51, 51))
        self.pushButton_25.setAutoFillBackground(False)
        self.pushButton_25.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_25.setText("")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_25.clicked.connect(self.on_click25)
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(250, 0, 51, 51))
        self.pushButton_26.setAutoFillBackground(False)
        self.pushButton_26.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_26.clicked.connect(self.on_click)
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(190, 70, 51, 51))
        self.pushButton_27.setAutoFillBackground(False)
        self.pushButton_27.setStyleSheet("QPushButton {\n"
"    \n"
"   background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"  \n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"  \n"
"    \n"
"\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"   background: transparent;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"   background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_27.setText("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 120, 88, 27))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_26.setText(_translate("MainWindow", "❌"))
        self.pushButton.setText(_translate("MainWindow", ""))
    def on_click(self):
        sys.exit()
    def on_click5(self):
         os.system("prinf hello 1")  
   

    def on_click6(self):
         os.system("printf 2")  
     
                             
    def on_click7(self):
         os.system("printf 3")  


    def on_click8(self):
         os.system("")  

    def on_click9(self):
         os.system("")  


    def on_click10(self):
         os.system("")  


    def on_click11(self):
         os.system("")  


    def on_click12(self):
         os.system("")  



    def on_click13(self):
         os.system("")  


    def on_click14(self):
         os.system("")  



    def on_click15(self):
         os.system("")  


    def on_click16(self):
         os.system("")  

    def on_click17(self):
         os.system("")  

    def on_click17(self):
         os.system("") 
    def on_click18(self):
         os.system("") 


    def on_click18(self):
         os.system("") 


    def on_click19(self):
         os.system("") 


    def on_click20(self):
         os.system("") 

    def on_click21(self):
         os.system("") 


    def on_click22(self):
         os.system("") 


    def on_click23(self):
         os.system("") 

    def on_click24(self):
         os.system("") 
         
    def on_click25(self):
         os.system("")          
         
         
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
